### PR TITLE
ReorderSam was having trouble when new dictionary is larger than old one

### LINKED ISSUE #974: ReorderSAM crashes with Invalid reference index -1 error after it is done
I receive this message for ReorderSAM, which I never saw before and I am not sure what it could be... Any hints?

[Sat Nov 11 18:34:17 GMT+01:00 2017] picard.sam.ReorderSam INPUT=382_rep1.cleaned3.s.bam OUTPUT=382_rep1.cleaned4.s.bam REFERENCE=GATK/Homo_sapiens_assembly38.fasta ALLOW_INCOMPLETE_DICT_CONCORDANCE=true CREATE_INDEX=true    ALLOW_CONTIG_LENGTH_DISCORDANCE=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Sat Nov 11 18:34:17 GMT+01:00 2017] Executing as ... on Linux 3.10.0-693.2.2.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_112-b15; Picard version: 2.9.0-1-gf5b9f50-SNAPSHOT

...
INFO    2017-11-11 18:40:37     ReorderSam        Processing chrUn_KI270742v1
INFO    2017-11-11 18:40:37     ReorderSam      Wrote 1294 reads
INFO    2017-11-11 18:40:37     ReorderSam        Processing chrUn_GL000216v2
INFO    2017-11-11 18:40:37     ReorderSam      Wrote 7644 reads
INFO    2017-11-11 18:40:37     ReorderSam        Processing chrUn_GL000218v1
INFO    2017-11-11 18:40:37     ReorderSam      Wrote 1574 reads
[Sat Nov 11 18:40:37 GMT+01:00 2017] picard.sam.ReorderSam done. Elapsed time: 6.33 minutes.
Runtime.totalMemory()=7847018496
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: Invalid reference index -1
        at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
        at picard.sam.ReorderSam.doWork(ReorderSam.java:124)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)

### PR DESCRIPTION
**Pull request by yfarjoun**
....and input type is BAM.

Also fixed logical problem that Reference was used both to open input (e.g. for cram) and to use as dictionary for new file.

Added a required input SEQUENCE_DICTIONARY and made REFERENCE_SEQUENCE not required.
This changes the API!

Added tests (was untested).

Refactored the code that writes a dictionary (using it in the test)

fixes #974.
supercedes #1073 

### Description

_Give your PR a **concise** yet **descriptive** title_
_Please explain the changes you made here._
_Explain the **motivation** for making this change. What existing problem does the pull request solve?_
_Mention any issues fixed, addressed or otherwise related to this pull request, including issue numbers or hard links for issues in other repos._
_You can delete these instructions once you have written your PR description._

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by cmnbroad** [comment]
@yfarjoun It looks like the tests pass when run standalone in IntelliJ (with either parser), and fail when run with the rest of the suite from gradle (with either parser). I'd suspect some kind of bad interaction or side-effect across tests.

**Comment by yfarjoun** [comment]
BTW, how do you run the non-legacy tests in intelliJ?

**Comment by cmnbroad** [comment]
@yfarjoun You need to set two system properties. One controls which parser is used, and one enables command line syntax translation, which you need when running existing tests and using the new parser. Details are https://github.com/broadinstitute/picard/wiki/Barclay-Transition-Notes#running-tests.

**Comment by yfarjoun** [comment]
perfect. thanks for the pointer...next time I'll RTFM... :-)

File: src/main/java/picard/sam/ReorderSam.java [hunk 1]
```diff
@@ -106,69 +117,58 @@
...
-                }
-                // don't forget the unmapped reads
-                writeReads(out, in.queryUnmapped(), newOrder, "unmapped");
+            printDictionary("SAM/BAM file", in.getFileHeader().getSequenceDictionary());
+            printDictionary("Reference", outputDictionary);
+            final Map<Integer, Integer> newOrder;
+            try {
+                newOrder = buildSequenceDictionaryMap(outputDictionary, in.getFileHeader().getSequenceDictionary());
+            } catch (PicardException e) {
+                log.error(e.getMessage());
```
Comment (danxmoran) [inline src/main/java/picard/sam/ReorderSam.java]: I'd just pass `e`, so the stack trace also gets logged.

File: src/test/java/picard/sam/ReorderSamTest.java [hunk 2]
```diff
@@ -0,0 +1,194 @@
...
+        setBuilder.addPair("split_pair2",
+                setBuilder.getHeader().getSequenceIndex("chr1"),
+                setBuilder.getHeader().getSequenceIndex("chr6"),
+                100, 200,
+                false, true, "36M",
+                "*", true, false, false,
+                false, 30);
+
+        { // same dictionary, but different order
+            final File dictionary = File.createTempFile("reorder-shuffle", ".dict");
```
Comment (danxmoran) [inline src/test/java/picard/sam/ReorderSamTest.java]: Could you push the `createTempFile` and `deleteOnExit` calls into the body of the test method, to cut duplication? If having a meaningful prefix is important than you could pass the string in as part of the `Object[]`.

File: src/test/java/picard/sam/ReorderSamTest.java [hunk 3]
```diff
@@ -0,0 +1,194 @@
...
+            dictionary.deleteOnExit();
+
+            final List<SAMSequenceRecord> sequences = new ArrayList<>(new SAMRecordSetBuilder().getHeader().getSequenceDictionary().getSequences());
+            Collections.shuffle(sequences, new Random(42));
```
Comment (danxmoran) [inline src/test/java/picard/sam/ReorderSamTest.java]: Ah, I guess if you push `createTempFile` into the test body then you can't write to the file here. I think you can solve that problem and DRY up even more if you pass a `Consumer<List<SAMSequenceRecord>>` to the test, instead of the final `List<SAMSequenceRecord>`. Then you can move the repeated `new ArrayList<>(...)` and `writeDictionary` calls into the body of the test too.

File: src/test/java/picard/sam/ReorderSamTest.java [hunk 4]
```diff
@@ -0,0 +1,194 @@
...
+ */
+public class ReorderSamTest extends CommandLineProgramTest {
+
+    @Override
+    public String getCommandLineProgramName() {
+        return ReorderSam.class.getSimpleName();
+    }
+
+    @DataProvider(name = "testDictionaryData")
+    public Iterator<Object[]> testDictionaryData() throws IOException {
```
Comment (pshapiro4broad) [inline src/test/java/picard/sam/ReorderSamTest.java]: I'm pretty sure this gets called at least once per test that requires the data. If the data is constant across all tests and is not modified by the tests it would be more efficient to create it in a `@BeforeClass` instead, since this does file I/O and other things that may take a while.

File: src/main/java/picard/sam/CreateSequenceDictionary.java [hunk 5]
```diff
@@ -185,40 +177,15 @@ protected int doWork() {
...
-            final String next = iterator.next();
-            if (current.equals(next)) {
-                OUTPUT.delete();
-                throw new PicardException("Sequence name " + current +
-                        " appears more than once in reference file");
-            }
-            current = next;
+        } catch (IllegalArgumentException e) {
+            OUTPUT.delete();
+            throw new PicardException(e.getMessage());
```
[the remark this answers is not in the document]
Comment (pshapiro4broad) [reply src/main/java/picard/sam/CreateSequenceDictionary.java]: Hard to tell what's intended here; do you need to export the `IllegalArgumentException` as a `PicardException` instead? Otherwise the `OUTPUT.delete()` code could go in a finally.

File: src/main/java/picard/sam/ReorderSam.java (hunk 1 above)
Comment (yfarjoun) [reply src/main/java/picard/sam/ReorderSam.java]: I thought we prefer not to emit stack traces if possible...but Ok.

File: src/test/java/picard/sam/ReorderSamTest.java (hunk 3 above)
Comment (yfarjoun) [reply src/test/java/picard/sam/ReorderSamTest.java]: done.

File: src/test/java/picard/sam/ReorderSamTest.java (hunk 4 above)
Comment (yfarjoun) [reply src/test/java/picard/sam/ReorderSamTest.java]: no more file IO in the data provider...so OK so leave as is?

File: src/test/java/picard/sam/ReorderSamTest.java (hunk 2 above)
Comment (yfarjoun) [reply src/test/java/picard/sam/ReorderSamTest.java]: done

File: src/main/java/picard/sam/CreateSequenceDictionary.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (yfarjoun) [reply src/main/java/picard/sam/CreateSequenceDictionary.java]: not good in a finally...since it only needs to happen if something is broken. added a comment to that effect.

**Comment by yfarjoun** [comment]
@pshapiro4broad this is ready for re-review.

File: src/test/java/picard/sam/testers/ValidateSamTester.java [hunk 6]
```diff
@@ -1,22 +1,35 @@
...
-        final int validateExitStatus = runPicardCommandLine(new String[]{"I=" + samFile.getAbsolutePath()});
-        Assert.assertEquals(validateExitStatus, 0);
+    public void setIgnoreError(final Collection<SAMValidationError.Type> errorsToIgnore){
+        ignoreErrors = new ArrayList<>(errorsToIgnore);
     }
 
+    public void assertSamValid(final File samFile) {
+        final List<String> args = new ArrayList<>();
+        args.add("I=" + samFile.getAbsolutePath());
+        ignoreErrors.forEach(s->args.add("IGNORE=" + s ));
```
Comment (pshapiro4broad) [inline src/test/java/picard/sam/testers/ValidateSamTester.java]: add whitespace
```suggestion
        ignoreErrors.forEach(s -> args.add("IGNORE=" + s ));
```

File: src/test/java/picard/sam/testers/ValidateSamTester.java [hunk 7]
```diff
@@ -1,22 +1,35 @@
...
+        final int validateExitStatus = runPicardCommandLine(args.toArray(new String[1 + ignoreErrors.size()]));
```
Comment (pshapiro4broad) [inline src/test/java/picard/sam/testers/ValidateSamTester.java]: In general it's more efficient to use `new String[0]`.
```suggestion
        final int validateExitStatus = runPicardCommandLine(args.toArray(new String[0]));
```

File: src/main/java/picard/sam/CreateSequenceDictionary.java [hunk 8]
```diff
@@ -237,6 +223,11 @@ protected int doWork() {
             throw new PicardException("File " + OUTPUT.getAbsolutePath() + " not found");
         } catch (IOException e) {
             throw new PicardException("Can't write to or close output file " + OUTPUT.getAbsolutePath());
+        } catch (IllegalArgumentException e) {
+            // in case of an unexpected error delete the file so that there isn't a
+            // truncated result which might be valid and wrong.
+            OUTPUT.delete();
```
[the remark this answers is not in the document]
Comment (yfarjoun) [reply src/main/java/picard/sam/CreateSequenceDictionary.java]: not this delete...I think Files.delete throws.

File: src/main/java/picard/sam/CreateSequenceDictionary.java [hunk 9]
```diff
@@ -318,6 +309,35 @@ private String md5Hash(final byte[] bytes) {
...
+
+        private void getNext() {
+            nextRecord = Optional.ofNullable(refSeqFile.nextSequence())
+                    .map(CreateSequenceDictionary.this::makeSequenceRecord)
+                    .orElse(null);
+        }
+
+        @Override
+        public SAMSequenceRecord next() {
+            final SAMSequenceRecord tempNext = nextRecord;
```
[the remark this answers is not in the document]
Comment (yfarjoun) [reply src/main/java/picard/sam/CreateSequenceDictionary.java]: OK.

File: src/main/java/picard/util/SequenceDictionaryUtils.java [hunk 10]
```diff
@@ -0,0 +1,107 @@
...
+        return SortingCollection.newInstance(
+                String.class,
+                new StringCodec(),
+                String::compareTo,
+                (int) Math.min(maxNamesInRam, Integer.MAX_VALUE),
+                tmpDir
+        );
+    }
+
+    private static class StringCodec implements SortingCollection.Codec<String> {
```
[the remark this answers is not in the document]
Comment (yfarjoun) [reply src/main/java/picard/util/SequenceDictionaryUtils.java]: I Agree....so it should be moved to htsjdk and then removed here...sharing it would require exposing a public class which would then require an api change to remove...

[the remark this answers is not in the document]
Comment (yfarjoun) [reply src/main/java/picard/util/SequenceDictionaryUtils.java]: also, I'm not sure I see where the code duplication is....

File: src/main/java/picard/sam/CreateSequenceDictionary.java [hunk 11]
```diff
@@ -111,62 +95,61 @@
...
-                ReferenceSequenceFileFactory.getReferenceSequenceFile(referenceFile, TRUNCATE_NAMES_AT_WHITESPACE);
-        ReferenceSequence refSeq;
+        final Iterable<SAMSequenceRecord> samSequenceRecordsIterable = getSamSequenceRecordsIterable();
+
         final List<SAMSequenceRecord> ret = new ArrayList<>();
         final Set<String> sequenceNames = new HashSet<>();
-        for (int numSequences = 0; numSequences < NUM_SEQUENCES && (refSeq = refSeqFile.nextSequence()) != null; ++numSequences) {
-            if (sequenceNames.contains(refSeq.getName())) {
-                throw new PicardException("Sequence name appears more than once in reference: " + refSeq.getName());
+        for(SAMSequenceRecord rec: samSequenceRecordsIterable){
```
Comment (pshapiro4broad) [inline src/main/java/picard/sam/CreateSequenceDictionary.java]: whitespace
```suggestion
        for (SAMSequenceRecord rec: samSequenceRecordsIterable) {
```

File: src/main/java/picard/sam/CreateSequenceDictionary.java [hunk 12]
```diff
@@ -216,27 +199,30 @@ protected int doWork() {
...
-            final ReferenceSequenceFile refSeqFile = ReferenceSequenceFileFactory.
-                    getReferenceSequenceFile(REFERENCE_SEQUENCE, TRUNCATE_NAMES_AT_WHITESPACE);
+            final Iterable<SAMSequenceRecord> samSequenceRecordIterable = getSamSequenceRecordsIterable();
             SAMSequenceDictionaryCodec samDictCodec = new SAMSequenceDictionaryCodec(writer);
 
             samDictCodec.encodeHeaderLine(false);
             // read reference sequence one by one and write its metadata
-            for (ReferenceSequence refSeq = refSeqFile.nextSequence(); refSeq != null; refSeq = refSeqFile.nextSequence()) {
-                final SAMSequenceRecord samSequenceRecord = makeSequenceRecord(refSeq);
+            for (SAMSequenceRecord samSequenceRecord :samSequenceRecordIterable){
```
Comment (pshapiro4broad) [inline src/main/java/picard/sam/CreateSequenceDictionary.java]: whitespace
```suggestion
            for (SAMSequenceRecord samSequenceRecord : samSequenceRecordIterable) {
```

**Comment by yfarjoun** [comment]
@pshapiro4broad back to you.

File: src/main/java/picard/sam/CreateSequenceDictionary.java [hunk 13]
```diff
@@ -111,62 +108,58 @@
...
     }
 
+    private Iterable<SAMSequenceRecord> getSamSequenceRecordsIterable() {
+        final SequenceDictionaryUtils.SamSequenceRecordsIterator samSequenceRecordIterator =
+                new SequenceDictionaryUtils.SamSequenceRecordsIterator(REFERENCE_SEQUENCE,
+                        TRUNCATE_NAMES_AT_WHITESPACE);
+        samSequenceRecordIterator.setGenomeAssembly(GENOME_ASSEMBLY);
+        samSequenceRecordIterator.setSpecies(SPECIES);
+        samSequenceRecordIterator.setUri(URI);
+        return () -> samSequenceRecordIterator;
```
Comment (pshapiro4broad) [inline src/main/java/picard/sam/CreateSequenceDictionary.java]: Is there a need to create the iterator at call time? You can defer creation until the returned iterator is called, e.g. 
```
        return () -> {
            final SequenceDictionaryUtils.SamSequenceRecordsIterator iterator =
                    new SequenceDictionaryUtils.SamSequenceRecordsIterator(REFERENCE_SEQUENCE,
                            TRUNCATE_NAMES_AT_WHITESPACE);
            iterator.setGenomeAssembly(GENOME_ASSEMBLY);
            iterator.setSpecies(SPECIES);
            iterator.setUri(URI);
            return iterator;
        };
```

File: src/main/java/picard/util/SequenceDictionaryUtils.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (pshapiro4broad) [reply src/main/java/picard/util/SequenceDictionaryUtils.java]: My mistake, the other copies aren't in picard. One copy is in an htsjdk test, `SortingCollectionTest.StringCodec`, and the other is in picard-private `StringSortingCollectionFactory.StringCodec`.

File: src/main/java/picard/sam/CreateSequenceDictionary.java (hunk 13 above)
Comment (yfarjoun) [reply src/main/java/picard/sam/CreateSequenceDictionary.java]: nice suggestion.
