### PR TITLE
Fix random seed in down sample

### LINKED ISSUE #935: DownsampleSam: RANDOM_SEED=null not working
### Affected tool(s)
DownsampleSam

### Affected version(s)
- v2.12.1
- Not tested, but the code in the master branch looks like it will produce the same behaviour

### Description 
Setting RANDOM_SEED to null induces a crash with this stacktrace:

```
Exception in thread "main" java.lang.NullPointerException
        at picard.sam.DownsampleSam.doWork(DownsampleSam.java:125)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)
```

It looks like the check whether RANDOM_SEED is null on line 121 just generates a random number generator. This is never used though and when making the htsjdk initialization on line 125, RANDOM_SEED is still null and hence the NullPointerException

#### Steps to reproduce
Run DownsampleSam with RANDOM_SEED='null'

#### Expected behavior
proper execution resulting in a downsampled bam file

#### Actual behavior
See description above

### PR DESCRIPTION
**Pull request by yfarjoun**
Fixes #935 so that RANDOM_SEED=null is a working option that results in random results.
----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

File: src/test/java/picard/sam/DownsampleSamTest.java [hunk 1]
```diff
@@ -0,0 +1,158 @@
...
+
+    //create a samfile with one tile and randomly placed reads within it.
+    @BeforeTest
+    void setupBuilder() throws IOException {
+        final int numReads = 10000;
+        final String flowCellBarcode = "TESTBARCODE";
+        final int maxX = 10000;
+        final int maxY = 20000;
+        final int minX = 1000;
+        final int minY = 2000;
```
Comment (meganshand) [inline src/test/java/picard/sam/DownsampleSamTest.java]: Is there a way to share code between tests? Presumably DownsampleSam shouldn't actually take the X:Y coordinates into account so maybe this isn't necessary?

File: src/test/java/picard/sam/DownsampleSamTest.java [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+        for (int i = 0; i < numReads; i++) {
+            final int x = rg.nextInt(maxX) + minX;
+            final int y = rg.nextInt(maxY) + minY;
+
+            final String readName = flowCellBarcode + separator + lane + separator + tile + separator + x + separator + y;
+            setBuilder.addPair(readName, 1, 1, 100);
+        }
+
+        tempDir = IOUtil.createTempDir("pds_test", "PositionalDownsampling");
+        tempSamFile = File.createTempFile("PositionalDownsampleSam", ".bam", tempDir);
```
Comment (meganshand) [inline src/test/java/picard/sam/DownsampleSamTest.java]: Do you still want to name these `PositionalDownsampleSam`?

File: src/test/java/picard/sam/DownsampleSamTest.java [hunk 3]
```diff
@@ -0,0 +1,158 @@
...
+    @AfterTest
+    private void tearDown() {
+        IOUtil.deleteDirectoryTree(tempDir);
+    }
+
+    @DataProvider(name = "ValidArgumentsTestProvider")
+    public Object[][] ValidArgumentsTestProvider() {
+        final List<Object[]> objects = new ArrayList<>();
+        for(final Strategy strategy : Strategy.values())
+            for( final Integer seed : new Integer[]{1, null})
```
Comment (meganshand) [inline src/test/java/picard/sam/DownsampleSamTest.java]: Should this new seed test be added to `PositionalDownsampleSam` as well?

Comment (yfarjoun) [reply src/test/java/picard/sam/DownsampleSamTest.java]: no...as PositionalDownsampleSam doesn't use a Random seed...

File: src/test/java/picard/sam/DownsampleSamTest.java (hunk 2 above)
Comment (yfarjoun) [reply src/test/java/picard/sam/DownsampleSamTest.java]: good catch...

**Comment by yfarjoun** [comment]
Commit message is wrong, but content is good....

thanks for the review @meganshand back to you.

File: src/test/java/picard/sam/DownsampleSamTest.java (hunk 3 above)
Comment (meganshand) [reply src/test/java/picard/sam/DownsampleSamTest.java]: huh, look at that :)
