### PR TITLE
FilterSamReads has a bug and can't filter read by read name.

### LINKED ISSUE #1070: bug report FilterSamReads
----

### Affected tool(s)
java -jar /home/xinhe/bin/picard.jar FilterSamReads 

### Affected version(s)
Latest public release version

### Description 
java -jar picard.jar FilterSamReads \
I=input.bam \
O=output.bam \
READ_LIST_FILE=read_names.txt \
FILTER=includeReadList

This command gives an error:
READ_LIST_FILE can only be specified when using FILTER=includeReadList, found value: read_names.txt

I went into the code and found the following code:
 protected String[] customCommandLineValidation() {

        List<String> errors = new ArrayList<>();

        if (INPUT.equals(OUTPUT)) errors.add("INPUT file and OUTPUT file must differ!");

        checkInputs(Filter.includeReadList, READ_LIST_FILE, "READ_LIST_FILE").ifPresent(errors::add);
        checkInputs(Filter.excludeAligned, READ_LIST_FILE, "READ_LIST_FILE").ifPresent(errors::add);
        checkInputs(Filter.includePairedIntervals, INTERVAL_LIST, "INTERVAL_LIST").ifPresent(errors::add);
        checkInputs(Filter.includeJavascript, JAVASCRIPT_FILE, "JAVASCRIPT_FILE").ifPresent(errors::add);

        if (!errors.isEmpty()) return errors.toArray(new String[errors.size()]);

        return super.customCommandLineValidation();
    }

    private Optional<String> checkInputs(final Filter filter, final File inputFile, final String inputFileVariable) {
        if (FILTER == filter && inputFile == null)
            return Optional.of(String.format("%s must be specified when using FILTER=%s, but it was null.", inputFileVariable, FILTER));
        if (FILTER != filter && inputFile != null)
            return Optional.of(String.format("%s can only be specified when using FILTER=%s, found value: %s", inputFileVariable, FILTER, inputFile));
        return Optional.empty();
    }

The checking logic is not correct because when providing 'READ_LIST_FILE' and 'FILTER=includeReadList', the code 

`checkInputs(Filter.excludeAligned, READ_LIST_FILE, "READ_LIST_FILE").ifPresent(errors::add);`

will always go into 

` if (FILTER != filter && inputFile != null)
return Optional.of(String.format("%s can only be specified when using FILTER=%s, found value: %s", inputFileVariable, FILTER, inputFile));` 

and generate the above error.

### PR DESCRIPTION
**Pull request by yfarjoun**
- fixed this bug
- added positive and negative tests

fixes #1070

### Description

_Give your PR a **concise** yet **descriptive** title_
_Please explain the changes you made here._
_Explain the **motivation** for making this change. What existing problem does the pull request solve?_
_Mention any issues fixed, addressed or otherwise related to this pull request, including issue numbers or hard links for issues in other repos._
_You can delete these instructions once you have written your PR description._

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

File: src/test/java/picard/sam/FilterSamReadsTest.java [hunk 1]
```diff
@@ -42,18 +47,115 @@ public String getCommandLineProgramName() {
...
+
+         try( final SAMFileWriter writer = new SAMFileWriterFactory()
+                .setCreateIndex(true).makeSAMWriter(builder.getHeader(), false, inputSam)) {
+
+             for (final SAMRecord record : builder) {
+                 writer.addAlignment(record);
+             }
+         }
+
+        final File reads = File.createTempFile(TEST_DIR.getAbsolutePath(),"reads");
```
Comment (gbggrant) [inline src/test/java/picard/sam/FilterSamReadsTest.java]: space after comma

File: src/test/java/picard/sam/FilterSamReadsTest.java [hunk 2]
```diff
@@ -42,18 +47,115 @@ public String getCommandLineProgramName() {
...
+        temp.deleteOnExit();
+
+        final String[] args = new String[]{
+                "INPUT=testdata/picard/sam/aligned.sam",
+                String.format("OUTPUT=%s", temp.getAbsolutePath()),
+                String.format("FILTER=%s", filter.toString()),
+                String.format("%s=%s", fileArgument, dummyFile),
+        };
+
+        // make sure results is successful
```
Comment (gbggrant) [inline src/test/java/picard/sam/FilterSamReadsTest.java]: update comment 'make sure program invocation failed - inputs validation error'

File: src/test/java/picard/sam/FilterSamReadsTest.java [hunk 3]
```diff
@@ -42,18 +47,115 @@ public String getCommandLineProgramName() {
...
+                {FilterSamReads.Filter.excludeAligned, "JAVASCRIPT_FILE"},
+                {FilterSamReads.Filter.includeAligned, "JAVASCRIPT_FILE"},
+                {FilterSamReads.Filter.includePairedIntervals, "JAVASCRIPT_FILE"},
+        };
+    }
+
+    @Test(dataProvider = "badArgumentCombinationsdata")
+    public void testBadArgumentCombinations(final FilterSamReads.Filter filter, final String fileArgument) throws IOException {
+
+        final File dummyFile = File.createTempFile(TEST_DIR.getAbsolutePath(),"dummy");
```
Comment (gbggrant) [inline src/test/java/picard/sam/FilterSamReadsTest.java]: space after comma

File: src/test/java/picard/sam/FilterSamReadsTest.java [hunk 4]
```diff
@@ -123,12 +226,19 @@ private FilterSamReads setupProgram(final File inputFile, final File inputSam, f
...
+                break;
+            case includeJavascript:
+                program.JAVASCRIPT_FILE = inputFile;
+                break;
+            case includeReadList:
+            case excludeReadList:
+                program.READ_LIST_FILE = inputFile;
+                break;
+            default:
+                throw new IllegalArgumentException("not configured for filter==" + filter);
```
Comment (gbggrant) [inline src/test/java/picard/sam/FilterSamReadsTest.java]: double '=' ?

File: src/test/java/picard/sam/FilterSamReadsTest.java [hunk 5]
```diff
@@ -42,18 +47,115 @@ public String getCommandLineProgramName() {
...
+        }
+
+        final File temp = File.createTempFile("FilterSamReads.output.", ".sam");
+        temp.deleteOnExit();
+
+        final String[] args = new String[]{
+                "INPUT=testdata/picard/sam/aligned.sam",
+                String.format("OUTPUT=%s", temp.getAbsolutePath()),
+                String.format("FILTER=%s", filter.toString()),
+                String.format("%s=%s", fileArgument, dummyFile),
```
Comment (gbggrant) [inline src/test/java/picard/sam/FilterSamReadsTest.java]: dummyFile.getAbsolutePath()
