### PR TITLE
Yf fix infinite loop md

### LINKED ISSUE #1146: endless while loop in estimateLibrarySize() in DuplicationMetrics.java
### Affected tool(s)

picard MarkDuplicates

### Affected version(s)

Latest public release version: 2.18.0

### Description 

The while loop in the following codes (in the function estimateLibrarySize() in DuplicationMetrics.java) never ends for some initial values of M, c and n with which the function f() will never return a negative value.

    while( f(M*c, c, n) >= 0 ) M *= 10.0;
     .
     .
     .
    private static double f(double x, double c, double n) {
            return c/x - 1 + Math.exp(-n/x);
    }

#### Steps to reproduce

Here is a short Java program to show the problem. The initial values of M, c and n are from real data.

    public class Loop
    {
        public static void main(String[] args)
        {
            // bug!!! f() never returns negative for initial values of
            double M = 100.0;
            double c = 357087881;
            double n = 357087883;
    
            while( f(M*c, c, n) >= 0 ) M *= 10.0; 
        }
    
        private static double f(double x, double c, double n) {
            System.err.println(c/x - 1 + Math.exp(-n/x));
            return c/x - 1 + Math.exp(-n/x);
        }
    }

#### Expected behavior

The while loop should exit for certain value of M.

#### Actual behavior

For certain values of M, c and n, such as, 100.0, 357087881 and 357087883 respectively, the function f() never returns a negative value.

#### Suggested correction

    while( f(M*c, c, n) > 0 ) M *= 10.0; 
    M *= 10.0;  // if necessary

### PR DESCRIPTION
**Pull request by yfarjoun**
- cleans whitespace
- fixes #1146 
- adds a test

### CODE REVIEW

File: src/main/java/picard/sam/DuplicationMetrics.java [hunk 1]
```diff
@@ -104,64 +120,67 @@ public void calculateDerivedMetrics() {
...
+            if (uniqueReadPairs >= readPairs || f(m * uniqueReadPairs, uniqueReadPairs, readPairs) < 0) {
                 throw new IllegalStateException("Invalid values for pairs and unique pairs: "
-                        + n + ", " + c);
-
+                        + readPairs + ", " + uniqueReadPairs);
             }
 
-            while( f(M*c, c, n) >= 0 ) M *= 10.0;
+            // find value of M, large enough to act as other side for bisection method
+            while (f(M * uniqueReadPairs, uniqueReadPairs, readPairs) > 0){
```
Comment (pshapiro4broad) [inline src/main/java/picard/sam/DuplicationMetrics.java]: missed a space before the `{`

File: src/main/java/picard/sam/DuplicationMetrics.java [hunk 2]
```diff
@@ -104,64 +120,67 @@ public void calculateDerivedMetrics() {
...
-                double r = (m+M)/2.0;
-                double u = f( r * c, c, n );
-                if ( u == 0 ) break;
-                else if ( u > 0 ) m = r;
-                else if ( u < 0 ) M = r;
+            // use bisection method (no more than 40 times) to find solution
+            for (int i = 0; i < 40; i++) {
+                double r = (m + M) / 2.0;
+                double u = f(r * uniqueReadPairs, uniqueReadPairs, readPairs);
+                if (u == 0) break;
```
Comment (pshapiro4broad) [inline src/main/java/picard/sam/DuplicationMetrics.java]: add `{` `}` for `if`/`else` here, e.g.
```
if (u == 0) {
    break;
} else if (u > 0) {
    m = r;
} else if (u < 0) {
    M = r;
}
```

**Comment by kbergin** [comment]
To clean up this repo, we are deleting stale branches that have been merged or closed. You have a short period of time to restore this branch if needed. Thanks!
