### PR TITLE
Only requiring that the input VCF be indexed if an INTERVAL is provided

### LINKED ISSUE #1477: CollectSamErrorMetrics does not accept a vanilla VCF
I ran `CollectSamErrorMetrics`  using version `2.21.9-SNAPSHOT` (btw why doesn't `picard --version` just work?) and a VCF file (`.vcf`) with no index.  This error message below is what I got.  I then tried compressing and indexing my VCF and the tool completed.  Nonetheless, there should either be a better error message that states an indexed VCF is required, or a VCF should be supported.

```
Exception in thread "main" java.lang.NullPointerException
	at picard.sam.SamErrorMetric.CollectSamErrorMetrics.closeVcfDataSource(CollectSamErrorMetrics.java:338)
	at picard.sam.SamErrorMetric.CollectSamErrorMetrics.processData(CollectSamErrorMetrics.java:386)
	at picard.sam.SamErrorMetric.CollectSamErrorMetrics.doWork(CollectSamErrorMetrics.java:483)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

### PR DESCRIPTION
**Pull request by yfarjoun**
- Only requiring that the input VCF be indexed if an INTERVAL is provided (since only then the vcf qill be queried)
- fixed the testing so it's a bit quicker (by running the code once on every input file rather than once for every test)
- fixed the javaDoc to describe when index is needed

fixes #1477

### CODE REVIEW

File: src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java [hunk 1]
```diff
@@ -294,14 +323,9 @@ public void testOneCovariateErrorMetrics(final String errorSubscript, final File
...
-    @DataProvider(name = "OneCovariateIndelErrorMetricsDataProvider")
+    @DataProvider()
     public Object[][] oneCovariateIndelErrorMetricsDataProvider() {
-        final File simpleSamWithBaseErrors1 = new File(TEST_DIR, "simpleSamWithBaseErrors1.sam");
-        final File simpleSamWithBaseErrors2 = new File(TEST_DIR, "simpleSamWithBaseErrors2.sam");
-        final File simpleSingleStrandConsensusSamWithBaseErrors = new File(TEST_DIR, "simpleSingleStrandConsensusSamWithBaseErrors.sam");
-        final File simpleDuplexConsensusSamWithBaseErrors = new File(TEST_DIR, "simpleDuplexConsensusSamWithBaseErrors.sam");
-        final File chrMReadsWithClips = new File(TEST_DIR, "chrMReadsWithClips.sam");
-        final int priorQ = 30;
+                final int priorQ = 30;
```
Comment (pshapiro4broad) [inline src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java:328]: Odd indent, or maybe github is showing the diff wrong?

File: src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java [hunk 2]
```diff
@@ -422,28 +446,10 @@ public void testOneCovariateErrorMetrics(final String errorSubscript, final File
...
 
-    @Test(dataProvider = "OneCovariateIndelErrorMetricsDataProvider")
+    @Test(dataProvider = "oneCovariateIndelErrorMetricsDataProvider")
     public void testOneCovariateIndelErrorMetrics(final String errorSubscript, final File samFile, final int priorQ, BaseErrorMetric expectedMetric) {
-        final File referenceFile = CHR_M_REFERENCE;
-        final File vcf = new File(TEST_DIR, "NIST.selected.vcf");
 
-        final File outputBaseFileName = new File(OUTPUT_DATA_PATH, "test");
-        final File errorByAll = new File(outputBaseFileName.getAbsolutePath() + errorSubscript);
-        errorByAll.deleteOnExit();
```
Comment (pshapiro4broad) [inline src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java:432]: It's hard to see in the diff but it looks like this file is no longer deleted on exit, is that correct?

File: src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java [hunk 3]
```diff
@@ -128,15 +140,52 @@ private static void parseDirective0(final String directive, final String extensi
...
+    @BeforeTest()
+    public void samMetricsProvider() {
+        final File[] files = new File[]{
+                simpleSamWithBaseErrors1,
+                simpleSamWithBaseErrors2,
+                simpleSingleStrandConsensusSamWithBaseErrors,
+                simpleDuplexConsensusSamWithBaseErrors,
+                chrMReadsWithClips};
+
+        OUTPUT_DATA_PATH = IOUtil.createTempDir("CollectSamErrorMetricsTest", null);
```
Comment (pshapiro4broad) [inline src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java:160]: This is run before every test, so this will create a new temp dir for each test, and store it in a static field. Is that what you want to do here? If each test gets its own temp dir, using a non-static field would make that clearer.

File: src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java [hunk 4]
```diff
@@ -128,15 +140,52 @@ private static void parseDirective0(final String directive, final String extensi
...
-    public Object[][] oneCovariateErrorMetricsDataProvider() {
-        final File simpleSamWithBaseErrors1 = new File(TEST_DIR, "simpleSamWithBaseErrors1.sam");
-        final File simpleSamWithBaseErrors2 = new File(TEST_DIR, "simpleSamWithBaseErrors2.sam");
-        final File simpleSingleStrandConsensusSamWithBaseErrors = new File(TEST_DIR, "simpleSingleStrandConsensusSamWithBaseErrors.sam");
-        final File simpleDuplexConsensusSamWithBaseErrors = new File(TEST_DIR, "simpleDuplexConsensusSamWithBaseErrors.sam");
-        final File chrMReadsWithClips = new File(TEST_DIR, "chrMReadsWithClips.sam");
-        final int priorQ = 30;
+    private final Map<File, File> errorMetrics = new HashMap<>();
+
+    private final File simpleSamWithBaseErrors1 = new File(TEST_DIR, "simpleSamWithBaseErrors1.sam");
```
Comment (pshapiro4broad) [inline src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java:145]: these can all be `static`

File: src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java [hunk 5]
```diff
@@ -128,15 +140,52 @@ private static void parseDirective0(final String directive, final String extensi
...
+                simpleSamWithBaseErrors1,
+                simpleSamWithBaseErrors2,
+                simpleSingleStrandConsensusSamWithBaseErrors,
+                simpleDuplexConsensusSamWithBaseErrors,
+                chrMReadsWithClips};
+
+        OUTPUT_DATA_PATH = IOUtil.createTempDir("CollectSamErrorMetricsTest", null);
+
+        for (final File file : files) {
+            final File vcf = new File(TEST_DIR, "NIST.selected.vcf");
```
Comment (pshapiro4broad) [inline src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java:163]: Does this mean that `testdata/picard/sam/BamErrorMetrics/NIST.selected.vcf.idx` can be deleted?

Comment (yfarjoun) [reply src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java:163]: yes...but a slightly different path will be tested....
