### PR TITLE
Fix "end" tag in inverted variants in liftover VCF.

### LINKED ISSUE #1258: LiftoverVCF + Badly formed variant context at location chr1:899903; getEnd()
Hi,

I am using LiftoverVCF to convert hg38 to hg19 and below is the issue. Could someone help to fix this or is it a bug with picard?

```
$ picard LiftoverVcf I=114.vcf O=114.hg19.vcf CHAIN=hg38ToHg19.over.chain R=ucsc_hg19.fa REJECT=114_rejected_variants.vcf
Picked up _JAVA_OPTIONS: -Xmx64g
13:18:31.625 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/homeappl/picard/picard-tools-2.18.10/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Dec 20 13:18:31 EET 2018] LiftoverVcf INPUT=114.vcf OUTPUT=114.hg19.vcf CHAIN=hg38ToHg19.over.chain REJECT=114_rejected_variants.vcf REFERENCE_SEQUENCE=ucsc_hg19.fa    WARN_ON_MISSING_CONTIG=false LOG_FAILED_INTERVALS=true WRITE_ORIGINAL_POSITION=false WRITE_ORIGINAL_ALLELES=false LIFTOVER_MIN_MATCH=1.0 ALLOW_MISSING_FIELDS_IN_HEADER=false RECOVER_SWAPPED_REF_ALT=false TAGS_TO_REVERSE=[AF] TAGS_TO_DROP=[MAX_AF] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Dec 20 13:18:31 EET 2018] Executing as XXXX on Linux 2.6.32-642.15.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_151-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.10-SNAPSHOT
INFO	2018-12-20 13:18:32	LiftoverVcf	Loading up the target reference genome.
INFO	2018-12-20 13:18:56	LiftoverVcf	Lifting variants over and sorting (not yet writing the output file.)
[Thu Dec 20 13:18:57 EET 2018] picard.vcf.LiftoverVcf done. Elapsed time: 0.42 minutes.
Runtime.totalMemory()=7120355328
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.tribble.TribbleException: Badly formed variant context at location chr1:899903; getEnd() was 899903 but this VariantContext contains an END key with value 964523
	at htsjdk.variant.variantcontext.VariantContext.validateStop(VariantContext.java:1321)
	at htsjdk.variant.variantcontext.VariantContext.validate(VariantContext.java:1294)
	at htsjdk.variant.variantcontext.VariantContext.<init>(VariantContext.java:401)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:494)
	at htsjdk.variant.variantcontext.VariantContextBuilder.make(VariantContextBuilder.java:488)
	at picard.util.LiftoverUtils.liftVariant(LiftoverUtils.java:108)
	at picard.vcf.LiftoverVcf.doWork(LiftoverVcf.java:389)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

```

### PR DESCRIPTION
**Pull request by yfarjoun**
### Description
Makes sure to update the "end" tag if it was previously present. The end tag is assumed to be valid if present. It will be recalculated if no symbolic allele is present, otherwise it is currently dropped. 

fixes #1258

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

File: src/main/java/picard/util/LiftoverUtils.java [hunk 1]
```diff
@@ -89,7 +84,16 @@ public static VariantContext liftVariant(final VariantContext source, final Inte
 
         builder.filters(source.getFilters());
         builder.log10PError(source.getLog10PError());
-        builder.attributes(source.getAttributes());
+
+        // If any of the source alleles is symbolic, do not populate the END tag (protecting things like <NON_REF> from
+        // getting screwed up in reverse-complemented variants
+        if (source.hasAttribute(VCFConstants.END_KEY) && builder.getAlleles().stream().noneMatch(Allele::isSymbolic)) {
```
Comment (jsotobroad) [inline src/main/java/picard/util/LiftoverUtils.java]: Should there even be an `END` attribute if there is no symbolic allele? (There probably is a reason to have it I just don't know it)

from the VCFv4.3 spec
```
END 1 Integer End position (for use with symbolic alleles)
```

File: src/main/java/picard/util/LiftoverUtils.java [hunk 2]
```diff
@@ -89,7 +84,16 @@ public static VariantContext liftVariant(final VariantContext source, final Inte
 
         builder.filters(source.getFilters());
         builder.log10PError(source.getLog10PError());
-        builder.attributes(source.getAttributes());
```
Comment (jsotobroad) [inline src/main/java/picard/util/LiftoverUtils.java]: why did this get deleted?

File: src/main/java/picard/util/LiftoverUtils.java (hunk 1 above)
Comment (yfarjoun) [reply src/main/java/picard/util/LiftoverUtils.java]: if you look at the original issue that spawned this PR you'll see an example of an insertion with an END allele.

File: src/main/java/picard/util/LiftoverUtils.java (hunk 2 above)
Comment (yfarjoun) [reply src/main/java/picard/util/LiftoverUtils.java]: because it already happens earlier in the code. specifically in lines picard/util/LiftoverUtils.java:154 or picard/util/LiftoverUtils.java:140 depending on the path taken.

Comment (yfarjoun) [reply src/main/java/picard/util/LiftoverUtils.java]: (the constructor that takes a vc copies the attributes)

File: src/main/java/picard/util/LiftoverUtils.java (hunk 1 above)
Comment (jsotobroad) [reply src/main/java/picard/util/LiftoverUtils.java]: but shouldn't we be getting rid of `END` in that case?

File: src/main/java/picard/util/LiftoverUtils.java (hunk 2 above)
Comment (jsotobroad) [reply src/main/java/picard/util/LiftoverUtils.java]: thanks!

File: src/main/java/picard/util/LiftoverUtils.java (hunk 1 above)
Comment (yfarjoun) [reply src/main/java/picard/util/LiftoverUtils.java]: hmmm. not sure. if someone has an "end" I don't mind moving it for them....but not in the case of an inversion (where I do remove it)

Comment (jsotobroad) [reply src/main/java/picard/util/LiftoverUtils.java]: I'm 50/50 on what should happen here but I'm happy leaving it up to you

File: src/test/java/picard/util/LiftoverUtilsTest.java [hunk 3]
```diff
@@ -17,15 +17,15 @@
 public class LiftoverUtilsTest {
 
     static final Allele A = Allele.create("A", false);
```
Comment (jsotobroad) [inline src/test/java/picard/util/LiftoverUtilsTest.java]: any reason this one isn't changed to `private`?

File: src/main/java/picard/util/LiftoverUtils.java [hunk 4]
```diff
@@ -89,7 +84,16 @@ public static VariantContext liftVariant(final VariantContext source, final Inte
...
+
+        // If any of the source alleles is symbolic, do not populate the END tag (protecting things like <NON_REF> from
```
Comment (jsotobroad) [inline src/main/java/picard/util/LiftoverUtils.java]: Could you add a test to make explicitly sure this is true
