### PR TITLE
Fix default PAR values for hg37 for FindMendelianViolations

### LINKED ISSUE #1598: FindMendelianViolations default XPAR co-ordinates for b37 incorrect
### Affected tool(s)
FindMendelianViolations

### Affected version(s)
Version:4.1.8.1 and several earlier versions at least

### Description 
Using the gatk FindMendelianViolations --help command to obtain information about this tool produces the following for the default XPAR regions:
--PSEUDO_AUTOSOMAL_REGIONS:String
List of chr:start-end for pseudo-autosomal regions on the female sex chromosome. Defaults
to HG19/b37 & HG38 coordinates. This argument may be specified 0 or more times. Default
value: [chrX:10000-2781479, X:10001-2649520, chrX:155701382-156030895,
X:59034050-59373566].

These co-ordinates are also replicated in the output file. From the GRC site the co-ordinates for the b37 regions should be X:600001-2699520 and X:154931044-155260560 whereas those used by default seem to correspond to the Y chromosome values for b37.
When trying to correct this issue by using the --PSEUDO_AUTOSOMAL_REGIONS option it simply adds the newly defined regions to the command rather than replacing the defaults.

### PR DESCRIPTION
**Pull request by yfarjoun**
(according to https://www.ncbi.nlm.nih.gov/grc/human)

- fixes #1598
- whitespace

### Description

_Give your PR a **concise** yet **descriptive** title_
_Please explain the changes you made here._
_Explain the **motivation** for making this change. What existing problem does the pull request solve?_
_Mention any issues fixed, addressed or otherwise related to this pull request, including issue numbers or hard links for issues in other repos._
_You can delete these instructions once you have written your PR description._

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

File: src/main/java/picard/vcf/MendelianViolations/FindMendelianViolations.java [hunk 1]
```diff
@@ -173,8 +173,9 @@
     @Argument(doc = "List of possible names for female sex chromosome(s)")
     public Set<String> FEMALE_CHROMS = CollectionUtil.makeSet("X", "chrX");
 
-    @Argument(doc = "List of chr:start-end for pseudo-autosomal regions on the female sex chromosome. Defaults to HG19/b37 & HG38 coordinates.")
-    public Set<String> PSEUDO_AUTOSOMAL_REGIONS = CollectionUtil.makeSet("X:10001-2649520", "X:59034050-59373566", "chrX:10000-2781479", "chrX:155701382-156030895");
+    @Argument(doc = "List of chr:start-end for pseudo-autosomal regions on the female sex chromosome. Defaults to HG19/b37 & HG38 coordinates.",
+    shortName = "PAR")
+    public Set<String> PSEUDO_AUTOSOMAL_REGIONS = CollectionUtil.makeSet("X:60001-2699520", "X:154931044-155260560", "chrX:10000-2781479", "chrX:155701383-156030895");
```
Comment (kachulis) [inline src/main/java/picard/vcf/MendelianViolations/FindMendelianViolations.java:178]:
```suggestion
    public Set<String> PSEUDO_AUTOSOMAL_REGIONS = CollectionUtil.makeSet("X:60001-2699520", "X:154931044-155260560", "chrX:10001-2781479", "chrX:155701383-156030895");
```
may as well fix hg38 as well

**Review by kachulis — APPROVED** [review]
Suggest fixing hg38 as well, then 👍

**Comment by yfarjoun** [comment]
@gbggrant who can review this?
