### PR TITLE
Must use a RIBOSOMAL_INTERVALS file if RRNA_FRAGMENT_PERCENTAGE = 0.0

### LINKED ISSUE #728: CollectRnaSeqMetrics Null Pointer Exception when RIBOSOMAL_INTERVALS are not given
If the`RIBOSOMAL_INTERVALS` option is not given and `RRNA_FRAGMENT_PERCENTAGE=0`, then [this if statement is always true](https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java#L168).  This leads to the following NPE:

```
Exception in thread "main" java.lang.NullPointerException
	at picard.analysis.directed.RnaSeqMetricsCollector$PerUnitRnaSeqMetricsCollector.acceptRecord(RnaSeqMetricsCollector.java:171)
	at picard.analysis.directed.RnaSeqMetricsCollector$PerUnitRnaSeqMetricsCollector.acceptRecord(RnaSeqMetricsCollector.java:98)
	at picard.metrics.MultiLevelCollector$AllReadsDistributor.acceptRecord(MultiLevelCollector.java:192)
	at picard.metrics.MultiLevelCollector.acceptRecord(MultiLevelCollector.java:315)
	at picard.analysis.CollectRnaSeqMetrics.acceptRead(CollectRnaSeqMetrics.java:164)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:138)
	at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:77)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```

A simple fix would be to not allow `RRNA_FRAGMENT_PERCENTAGE=0` if `RIBOSOMAL_INTERVALS=null`.

### PR DESCRIPTION
**Pull request by ronlevine**
### Description

Fixes #728 
If the RIBOSOMAL_INTERVALS option is not given and RRNA_FRAGMENT_PERCENTAGE=0, then [this if statement](https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java#L164) is always true and [rec.getReadLength()](https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java#L167) will throw an `NullPointerException` since there no records in the input SAM file.

Fixed by throwing and exception if `RRNA_FRAGMENT_PERCENTAGE=0` and `RIBOSOMAL_INTERVALS` is not set or the file is empty.

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [X] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [X] All tests passing on Travis

#### Review
- [X] Final thumbs-up from reviewer
- [X] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

File: src/main/java/picard/analysis/CollectRnaSeqMetrics.java [hunk 1]
```diff
@@ -137,6 +137,11 @@ public static void main(final String[] argv) {
     @Override
     protected void setup(final SAMFileHeader header, final File samFile) {
 
+        // No ribosomal intervals and rRNA fragment percentage = 0
+        if ( (RIBOSOMAL_INTERVALS == null || RIBOSOMAL_INTERVALS.length() == 0) && RRNA_FRAGMENT_PERCENTAGE == 0 ) {
+            throw new PicardException("Must use a RIBOSOMAL_INTERVALS file if RRNA_FRAGMENT_PERCENTAGE = 0.0");
+        }
+
```
Comment (nh13) [inline src/main/java/picard/analysis/CollectRnaSeqMetrics.java]: 1. I'd override `customCommandLineValidation` and move this there:
```
@Override
protected String[] customCommandLineValidation() {
  // No ribosomal intervals and rRNA fragment percentage = 0
  if ( (RIBOSOMAL_INTERVALS == null || RIBOSOMAL_INTERVALS.length() == 0) && RRNA_FRAGMENT_PERCENTAGE == 0 ) {
    return new String[]{"Must use a RIBOSOMAL_INTERVALS file if RRNA_FRAGMENT_PERCENTAGE = 0.0"};
  }
  return super.customCommandLineValidation();
}
```
2. I think that you can remove the empty file check here, since we could have a non-empty interval list (just the sequence dictionary) but no intervals, which brings me to...

3. I think if someone goes to the trouble if providing a ribosomal intervals file and there are none read in, we should at least log a warning if not return an error.  This check could be in `makeOverlapDetector`.

File: src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java [hunk 2]
```diff
@@ -112,7 +115,54 @@ public void testBasic() throws Exception {
...
+                "REF_FLAT=" + getRefFlatFile(sequence).getAbsolutePath(),
+                "RIBOSOMAL_INTERVALS=" + rRnaIntervalsPath,
+                "RRNA_FRAGMENT_PERCENTAGE=" + 0.0,
+                "STRAND_SPECIFICITY=SECOND_READ_TRANSCRIPTION_STRAND",
+                "IGNORE_SEQUENCE=" + ignoredSequence
+        };
+        Assert.assertEquals(runPicardCommandLine(args), 0);
+    }
+
+        @Test
```
Comment (nh13) [inline src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java]: Indentation

File: src/main/java/picard/analysis/CollectRnaSeqMetrics.java (hunk 1 above)
Comment (ronlevine) [inline src/main/java/picard/analysis/CollectRnaSeqMetrics.java]: - Moved `No ribosomal intervals and rRNA fragment percentage = 0`  Overrode `customCommandLineValidation`
- Removed the empty file check, not needed. The code throws an IllegalStateException if the header is missing.
- If the ribosomal intervals file is missing intervals, an exception is thrown from `makeOverlapDetector`. Just having a waning with `RRNA_FRAGMENT_PERCENTAGE = 0.0` have [this if statement](https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java#L164) always true

Comment (ronlevine) [inline src/main/java/picard/analysis/CollectRnaSeqMetrics.java]: @nh13 Please take a look.

**Comment by nh13** [comment]
Will do, likely by the end of the week given some higher priorities.  Thanks for getting this done!

File: src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java (hunk 2 above)
Comment (ronlevine) [inline src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java]: Done

**Comment by ronlevine** [comment]
@nh13 Will you have time to look at this?

File: src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java [hunk 3]
```diff
@@ -60,12 +60,15 @@ public RnaSeqMetricsCollector(final Set<MetricAccumulationLevel> accumulationLev
...
 
-    public static OverlapDetector<Interval> makeOverlapDetector(final File samFile, final SAMFileHeader header, final File ribosomalIntervalsFile) {
+    public static OverlapDetector<Interval> makeOverlapDetector(final File samFile, final SAMFileHeader header, final File ribosomalIntervalsFile, final double rrnaFragmentPercentage) {
 
         OverlapDetector<Interval> ribosomalSequenceOverlapDetector = new OverlapDetector<Interval>(0, 0);
         if (ribosomalIntervalsFile != null) {
 
             final IntervalList ribosomalIntervals = IntervalList.fromFile(ribosomalIntervalsFile);
+            if ( ribosomalIntervals.size() == 0 && rrnaFragmentPercentage == 0.0) {
+                throw new PicardException("The RIBOSOMAL_INTERVALS file, " + ribosomalIntervalsFile.getAbsolutePath() + " must containn intervals if the rRNA fragment percentage = 0");
```
Comment (nh13) [inline src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java]: I wasn't suggesting to pass in `rrnaFragmentPercentage` to this method (I don't think it is appropriate), but ihnstead log a warning if `ribosomalIntervals.size() == 0`.

File: src/main/java/picard/analysis/CollectRnaSeqMetrics.java [hunk 4]
```diff
@@ -135,6 +135,17 @@ public static void main(final String[] argv) {
...
 
     @Override
+    protected String[] customCommandLineValidation() {
+
+        // No ribosomal intervals file and rRNA fragment percentage = 0
+        if ( RIBOSOMAL_INTERVALS == null && RRNA_FRAGMENT_PERCENTAGE == 0 ) {
+            throw new PicardException("Must use a RIBOSOMAL_INTERVALS file if RRNA_FRAGMENT_PERCENTAGE = 0.0");
+        }
+
+        return super.customCommandLineValidation();
```
Comment (nh13) [inline src/main/java/picard/analysis/CollectRnaSeqMetrics.java]: Remove the two unneeded newlines.

File: src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java [hunk 5]
```diff
@@ -112,6 +115,59 @@ public void testBasic() throws Exception {
...
+                "INPUT=" + samFile.getAbsolutePath(),
+                "OUTPUT=" + metricsFile.getAbsolutePath(),
+                "REF_FLAT=" + getRefFlatFile(sequence).getAbsolutePath(),
+                "RIBOSOMAL_INTERVALS=" + rRnaIntervalsPath,
+                "RRNA_FRAGMENT_PERCENTAGE=" + 0.0,
+                "STRAND_SPECIFICITY=SECOND_READ_TRANSCRIPTION_STRAND",
+                "IGNORE_SEQUENCE=" + ignoredSequence
+        };
+        Assert.assertEquals(runPicardCommandLine(args), 0);
+    }
```
Comment (nh13) [inline src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java]: I don't see a test where it fails if the intervals file is empty and `RRNA_FRAGMENT_PERCENTAGE=0`

Comment (ronlevine) [inline src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java]: `File.createTempFile("tmp.rRna.", ".interval_list")` is an empty intervals file.

File: src/main/java/picard/analysis/CollectRnaSeqMetrics.java (hunk 4 above)
Comment (ronlevine) [inline src/main/java/picard/analysis/CollectRnaSeqMetrics.java]: Done.

File: src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java (hunk 3 above)
Comment (ronlevine) [inline src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java]: Done.

File: src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java (hunk 5 above)
Comment (ronlevine) [inline src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java]: There's a test where the intervals file has a header but no intervals and `RRNA_FRAGMENT_PERCENTAGE=0`. An empty intervals file will fail regardless of the value of `RRNA_FRAGMENT_PERCENTAGE`:
```
java.lang.IllegalStateException: Interval list file must contain header. 

at htsjdk.samtools.util.IntervalList.fromReader(IntervalList.java:455)
at htsjdk.samtools.util.IntervalList.fromFile(IntervalList.java:400)
at picard.analysis.directed.RnaSeqMetricsCollector.makeOverlapDetector(RnaSeqMetricsCollector.java:69)
at picard.analysis.CollectRnaSeqMetrics.setup(CollectRnaSeqMetrics.java:155)
at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:122)
at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:77)
at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:99)
at picard.cmdline.CommandLineProgramTest.runPicardCommandLine(CommandLineProgramTest.java:48)
at picard.analysis.CollectRnaSeqMetricsTest.testNoIntevalsNoFragPercentage(CollectRnaSeqMetricsTest.java:169)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
at org.testng.TestRunner.privateRun(TestRunner.java:782)
at org.testng.TestRunner.run(TestRunner.java:632)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
at org.testng.SuiteRunner.run(SuiteRunner.java:268)
```

**Comment by ronlevine** [comment]
@nh13 Responded to comments, back to you.
